name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '5.1.x'
          dune-cache: true
          allow-prerelease-opam: true

      - name: Deps
        run: opam install odig linol linol-lwt

      - name: Build
        run: opam exec -- odig odoc --cache-dir=_doc/ linol linol-lwt || (odig log -e ; exit 1)

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_doc/html
          enable_jekyll: false
